apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: docker.io/emilijalakinska/go-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: GREETING_MESSAGE
              value: "Hello from EKS"
